spring:
  application:
    name: todoapi
  datasource:
    url: jdbc:h2:mem:todoapidb
    username: admin
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate / update / create / creat-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
